FROM google/cloud-sdk:alpine

RUN apk --update add \
  python3 \
  py3-pip \
  py3-wheel \
  py3-setuptools \
  jq \
  python3-dev \
  git \
  openssh-client \
  zlib-dev \
  libc-dev \
  libffi-dev \
  openssl-dev \
  gcc \
  curl \
  make \
  cmake \
  binutils \
  && pip install pipenv
