#!/usr/bin/env python3

import argparse
import json
import os
from pathlib import Path

import jinja2

DEFAULT_PLATFORMS = "linux/amd64,linux/arm64"
SINGLE_ARCH_IMAGES = {"debezium", "gcloud"}
SINGLE_ARCH_TAGS = {
    "rust": {"sccache", "sccache-scheduler", "sccache-server"},
}


def scan_images(repo_root):
    """
    Scan a project for all the files and directories.
    """
    projects = {}

    # Scan the image_name is the directory in top level
    # The image_tag is the directory in the image_name directory
    for image_name in sorted(os.listdir(repo_root)):
        image_dir = repo_root / image_name
        if image_dir.is_dir():
            projects[image_name] = []
            for image_tag in sorted(os.listdir(image_dir)):
                check = image_dir / image_tag / "Dockerfile"
                if check.is_file():
                    projects[image_name].append(image_tag)

    # Filter out the empty image_tags
    projects = {k: v for k, v in projects.items() if v}

    return projects


def resolve_platform_expression(image_name):
    """Resolve workflow expression for job-level IMAGE_PLATFORMS."""
    if image_name in SINGLE_ARCH_IMAGES:
        return "linux/amd64"

    single_arch_tags = sorted(SINGLE_ARCH_TAGS.get(image_name, set()))
    if not single_arch_tags:
        return DEFAULT_PLATFORMS

    overrides = json.dumps(single_arch_tags)
    return (
        "${{ contains(fromJSON('"
        + overrides
        + "'), matrix.tags) && 'linux/amd64' || '"
        + DEFAULT_PLATFORMS
        + "' }}"
    )


def get_template_workflows():
    """jinja2 template for Github workflows from string"""

    template = """# Generated by gen.py script
# Do not edit this file manually

name: Build and Push
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

{% raw %}
env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
{% endraw %}

jobs:
{%- for image_name, image_tags in images.items() %}
  {{ image_name }}:
    name: Build {{ image_name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tags:
          {%- for image_tag in image_tags %}
          - {{ image_tag }}
          {%- endfor %}
    env:
      IMAGE_NAME: {{ image_name }}
      IMAGE_TAG: '{% raw %}${{ matrix.tags }}{% endraw %}'
      IMAGE_PLATFORMS: {{ image_platforms[image_name] }}
    {%- raw %}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
             src:
              - '${{ env.IMAGE_NAME }}/${{ matrix.tags }}/**'
              - '.github/workflows/ci.yaml'

      - name: Log in to the Container registry
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.changes.outputs.src == 'true'
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        if: steps.changes.outputs.src == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO }}
          tags: |
            type=raw,value=${{ matrix.tags }}
            type=sha,format=short

      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}
          context: ${{ github.workspace }}
          file: ./${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Image digest
        if: steps.changes.outputs.src == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Run Trivy vulnerability scan
        if: steps.changes.outputs.src == 'true' && github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ matrix.tags }}'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          exit-code: '0'

      - name: Run Trivy config scan
        if: steps.changes.outputs.src == 'true'
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'config'
          scan-ref: './${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}/Dockerfile'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
    {%- endraw %}
{% endfor -%}
    """

    return template


def get_template_readme():
    """jinja2 template for README.md from string"""

    template = """

{%- for image_name, image_tags in images.items() | sort %}
- [`{{ image_name }}`](#{{ image_name }})
{%- for image_tag in image_tags | sort %}
    - [`ghcr.io/duyet/docker-images:{{ image_tag }}`](#{{ (image_name + image_tag).lower().replace(" ", "").replace(".", "") }})
{%- endfor %}
{%- endfor %}

{% for image_name, image_tags in images.items() %}
## `{{ image_name }}`

{%- for image_tag in image_tags %}

### [`{{ image_name }}/{{ image_tag }}`]({{ image_name }}/{{ image_tag }}/Dockerfile)

Install from the command line

```bash
docker pull ghcr.io/duyet/docker-images:{{ image_tag }}
```

Use as base image in Dockerfile:

```Dockerfile
FROM ghcr.io/duyet/docker-images:{{ image_tag }}
```
{% endfor %}
{% endfor -%}
    """

    return template


def build_workflows(images):
    """Build the workflows yaml for the images."""

    # Get the jinja2 template
    template = jinja2.Template(get_template_workflows())

    # Build the workflows
    image_platforms = {
        name: resolve_platform_expression(name) for name in images
    }
    workflows = template.render(images=images, image_platforms=image_platforms)

    return workflows


def build_readme(images):
    """Build the README.md for the images."""

    # Get the jinja2 template
    template = jinja2.Template(get_template_readme())

    # Build the workflows
    return template.render(images=images)


def parse_args():
    parser = argparse.ArgumentParser(description="Generate workflow and README image list.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the workflow YAML and skip writing files.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    repo_root = Path(__file__).resolve().parent
    images = scan_images(repo_root)
    workflows = build_workflows(images)

    if args.dry_run:
        print(workflows)
        raise SystemExit(0)

    # Write the workflows to the github workflows directory
    target = repo_root / ".github/workflows/ci.yaml"
    with open(target, "w", encoding="utf-8") as f:
        f.write(workflows)
        print(f"Generated workflows to {target}")

    # Generate the README.md
    # Replace content between <!-- BEGIN IMAGE LIST --> and <!-- END IMAGE LIST -->
    # with the list of images
    readme_content = build_readme(images)
    readme_path = repo_root / "README.md"
    with open(readme_path, "r", encoding="utf-8") as f:
        begin_marker = "<!-- BEGIN IMAGE LIST -->"
        end_marker = "<!-- END IMAGE LIST -->"
        content = f.read()
        start = content.find(begin_marker)
        end = content.find(end_marker)
        if start == -1 or end == -1 or start >= end:
            raise ValueError("README markers not found or invalid order")
        content = content[:start] + begin_marker + readme_content + content[end:]

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)
        print("Generated README.md")
