#!/usr/bin/env python3

import argparse
import json
import os
import sys
from pathlib import Path

import jinja2

DEFAULT_PLATFORMS = "linux/amd64,linux/arm64"
SINGLE_ARCH_IMAGES = {"debezium", "gcloud"}
SINGLE_ARCH_TAGS = {
    "rust": {"sccache", "sccache-scheduler", "sccache-server"},
}


def scan_images(repo_root):
    """
    Scan a project for all the files and directories.
    """
    projects = {}

    # Scan the image_name is the directory in top level
    # The image_tag is the directory in the image_name directory
    for image_name in sorted(os.listdir(repo_root)):
        image_dir = repo_root / image_name
        if image_dir.is_dir():
            projects[image_name] = []
            for image_tag in sorted(os.listdir(image_dir)):
                check = image_dir / image_tag / "Dockerfile"
                if check.is_file():
                    projects[image_name].append(image_tag)

    # Filter out the empty image_tags
    projects = {k: v for k, v in projects.items() if v}

    return projects


def resolve_platform_expression(image_name):
    """Resolve workflow expression for job-level IMAGE_PLATFORMS."""
    if image_name in SINGLE_ARCH_IMAGES:
        return "linux/amd64"

    single_arch_tags = sorted(SINGLE_ARCH_TAGS.get(image_name, set()))
    if not single_arch_tags:
        return DEFAULT_PLATFORMS

    overrides = json.dumps(single_arch_tags)
    return (
        "${{ contains(fromJSON('"
        + overrides
        + "'), matrix.tags) && 'linux/amd64' || '"
        + DEFAULT_PLATFORMS
        + "' }}"
    )


def get_template_workflows():
    """jinja2 template for Github workflows from string"""

    template = """# Generated by gen.py script
# Do not edit this file manually

name: Build and Push
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

  workflow_dispatch:

{% raw %}
concurrency:
  # Serialize runs per ref. cancel-in-progress is intentionally false:
  # cancelling a run mid `docker buildx push` writes a multi-arch manifest
  # index that points at a child manifest that never landed (the published
  # node_22.14.0_alpine amd64 manifest was orphaned this way by overlapping
  # pushes on 2026-06-10). At most one *running* run per ref.
  #
  # `queue` is the other half of that decision, and the default is lossy.
  # With `single`, GitHub keeps one running run and one pending run, and
  # cancels the pending one when a third arrives. Four merges inside 24
  # minutes on 2026-09-28 dropped three of the four master runs before any
  # of them started a job, and the one that survived did not cover for
  # them. The paths filter is not the saving grace it looks like: every
  # family's filter also matches `.github/workflows/ci.yaml`, so a commit
  # that regenerates the workflow rebuilds all 68 images. That survivor
  # was the *oldest* of the four, so it published the oldest tree of them
  # all: `minio_latest` and `gcloud_debian_python3` were left published
  # from a commit behind master, and a whole python tag family 404'd.
  # Every check stayed green throughout, because nothing asserted that the
  # registry agreed with master (issue #97) — the `published` job does.
  #
  # `queue: max` holds up to 100 pending runs instead of replacing them, so
  # a burst of merges drains in order rather than evaporating. It is only
  # valid alongside cancel-in-progress: false, which is what the orphaned
  # manifest above requires anyway.
  group: ci-${{ github.ref }}
  cancel-in-progress: false
  queue: max

env:
  REGISTRY: ghcr.io
  REPO: ${{ github.repository }}
{% endraw %}

jobs:
{%- for image_name, image_tags in images.items() %}
  {{ image_name }}:
    name: Build {{ image_name }}
    runs-on: ubuntu-latest
    strategy:
      # A single job failing (or being cancelled) must not abort a sibling
      # mid `docker buildx push`, which orphans manifest children. Each tag
      # is independent; let them all run to completion.
      fail-fast: false
      matrix:
        tags:
          {%- for image_tag in image_tags %}
          - {{ image_tag }}
          {%- endfor %}
    env:
      IMAGE_NAME: {{ image_name }}
      IMAGE_TAG: '{% raw %}${{ matrix.tags }}{% endraw %}'
      IMAGE_PLATFORMS: {{ image_platforms[image_name] }}
    {%- raw %}
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - uses: dorny/paths-filter@0e4a8c6effa4802afeda77dc8d303f8176d7dfad # v3
        id: changes
        with:
          filters: |
             src:
              - '${{ env.IMAGE_NAME }}/${{ matrix.tags }}/**'
              - '.github/workflows/ci.yaml'

      - name: Log in to the Container registry
        if: steps.changes.outputs.src == 'true'
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        if: steps.changes.outputs.src == 'true'
        id: buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Extract metadata (tags, labels) for Docker
        if: steps.changes.outputs.src == 'true'
        id: meta
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051 # v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REPO }}
          tags: |
            type=raw,value=${{ matrix.tags }}
            type=sha,format=short

      - name: Build and push
        if: steps.changes.outputs.src == 'true'
        id: docker_build
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          platforms: ${{ env.IMAGE_PLATFORMS }}
          context: ${{ github.workspace }}
          file: ./${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}

      - name: Image digest
        if: steps.changes.outputs.src == 'true'
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Generate Trivy vulnerability report
        if: steps.changes.outputs.src == 'true' && github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ matrix.tags }}'
          format: 'json'
          output: 'trivy-report.json'
          exit-code: '0'

      - name: Upload Trivy scan results artifact
        if: steps.changes.outputs.src == 'true' && github.event_name != 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: 'trivy-report-${{ matrix.tags }}'
          path: 'trivy-report.json'
          retention-days: 30

      - name: Run Trivy vulnerability scan (sarif)
        if: steps.changes.outputs.src == 'true' && github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ matrix.tags }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        if: steps.changes.outputs.src == 'true' && github.event_name != 'pull_request'
        uses: github/codeql-action/upload-sarif@1190a975f95ce23525efb6a3fc21ea29567c1b52 # v3
        with:
          sarif_file: 'trivy-results.sarif'
          category: '${{ matrix.tags }}'

      - name: Report HIGH/CRITICAL vulnerabilities
        if: steps.changes.outputs.src == 'true' && github.event_name != 'pull_request'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          image-ref: '${{ env.REGISTRY }}/${{ env.REPO }}:${{ matrix.tags }}'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true
          exit-code: '0'
          skip-setup-trivy: true

      - name: Run Trivy config scan
        if: steps.changes.outputs.src == 'true'
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: 'config'
          scan-ref: './${{ env.IMAGE_NAME }}/${{ env.IMAGE_TAG }}/Dockerfile'
          format: 'table'
          severity: 'CRITICAL,HIGH,MEDIUM'
          exit-code: '0'
    {%- endraw %}
{% endfor -%}

{% raw %}
  published:
    name: Assert published matches master
    runs-on: ubuntu-latest
    # Runs after every build, and runs even if one failed: a failed build leaves
    # its tag unpublished, which is exactly the state this gate exists to catch.
    {%- endraw %}
    needs: [{% for image_name in images.keys() %}{{ image_name }}{% if not loop.last %}, {% endif %}{% endfor %}]
    {%- raw %}
    if: always() && github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          # The gate compares the registry against master's tree, so it must see
          # the merge commit that triggered this run, not the branch tip.
          ref: ${{ github.event.after }}
          # Full history, not a shallow clone: the gate decides staleness with
          # `git log -1 -- <image dir>` and `git merge-base --is-ancestor`, and
          # neither means anything without the ancestry between commits.
          fetch-depth: 0

      - name: Collect the last commit that touched each image
        run: ./tools/collect_commit_shas.sh

      - name: Assert every tag is published from a commit at or after master
        run: |
          set -euo pipefail
          python3 tools/verify_published.py --tree tree.txt --commits commit-shas.txt

      - name: Publish state on failure
        if: failure()
        run: |
          {
            echo '## Registry does not match master'
            echo
            echo 'A tag is missing, could not be read, or was published from a'
            echo 'commit older than the one that last touched its directory.'
            echo '`master` and the registry disagree, so no tag can be trusted'
            echo 'until this is resolved. See issue #97.'
            echo
            echo '```'
            python3 tools/verify_published.py --tree tree.txt --commits commit-shas.txt || true
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
{%- endraw %}

"""

    return template


def get_template_readme():
    """jinja2 template for README.md from string"""

    template = """

{%- for image_name, image_tags in images.items() | sort %}
- [`{{ image_name }}`](#{{ image_name }})
{%- for image_tag in image_tags | sort %}
    - [`ghcr.io/duyet/docker-images:{{ image_tag }}`](#{{ (image_name + image_tag).lower().replace(" ", "").replace(".", "") }})
{%- endfor %}
{%- endfor %}

{% for image_name, image_tags in images.items() %}
## `{{ image_name }}`

{%- for image_tag in image_tags %}

### [`{{ image_name }}/{{ image_tag }}`]({{ image_name }}/{{ image_tag }}/Dockerfile)

{% if blurbs.get(image_name, {}).get(image_tag) -%}
{{ blurbs[image_name][image_tag] }}

{% endif -%}
Install from the command line

```bash
docker pull ghcr.io/duyet/docker-images:{{ image_tag }}
```

Use as base image in Dockerfile:

```Dockerfile
FROM ghcr.io/duyet/docker-images:{{ image_tag }}
```
{% endfor %}
{% endfor -%}
    """

    return template


def build_workflows(images):
    """Build the workflows yaml for the images."""

    # Get the jinja2 template
    template = jinja2.Template(get_template_workflows())

    # Build the workflows
    image_platforms = {
        name: resolve_platform_expression(name) for name in images
    }
    workflows = template.render(images=images, image_platforms=image_platforms)

    return workflows


def load_blurbs(repo_root, images):
    """Optional blurb.md next to a Dockerfile is copied into the README."""
    blurbs = {}
    for image_name, image_tags in images.items():
        blurbs[image_name] = {}
        for image_tag in image_tags:
            path = repo_root / image_name / image_tag / "blurb.md"
            if path.is_file():
                blurbs[image_name][image_tag] = path.read_text(encoding="utf-8").strip()
    return blurbs


def build_readme(images, blurbs=None):
    """Build the README.md for the images."""

    # Get the jinja2 template
    template = jinja2.Template(get_template_readme())

    # Build the workflows
    return template.render(images=images, blurbs=blurbs or {})


def parse_args():
    parser = argparse.ArgumentParser(description="Generate workflow and README image list.")
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the workflow YAML and skip writing files.",
    )
    return parser.parse_args()


if __name__ == "__main__":
    args = parse_args()
    repo_root = Path(__file__).resolve().parent
    images = scan_images(repo_root)
    workflows = build_workflows(images)

    if args.dry_run:
        # Write, do not print: print() appends a newline that f.write() below
        # does not, so a preview would never be byte-identical to the file a
        # real run produces. That phantom trailing blank line is the diff every
        # caller must learn to ignore.
        sys.stdout.write(workflows)
        raise SystemExit(0)

    # Write the workflows to the github workflows directory
    target = repo_root / ".github/workflows/ci.yaml"
    with open(target, "w", encoding="utf-8") as f:
        f.write(workflows)
        print(f"Generated workflows to {target}")

    # Generate the README.md
    # Replace content between <!-- BEGIN IMAGE LIST --> and <!-- END IMAGE LIST -->
    # with the list of images
    readme_content = build_readme(images, load_blurbs(repo_root, images))
    readme_path = repo_root / "README.md"
    with open(readme_path, "r", encoding="utf-8") as f:
        begin_marker = "<!-- BEGIN IMAGE LIST -->"
        end_marker = "<!-- END IMAGE LIST -->"
        content = f.read()
        start = content.find(begin_marker)
        end = content.find(end_marker)
        if start == -1 or end == -1 or start >= end:
            raise ValueError("README markers not found or invalid order")
        content = content[:start] + begin_marker + readme_content + content[end:]

    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(content)
        print("Generated README.md")
