#!/usr/bin/env python3

import os
import sys
import jinja2


def scan_images():
    """
    Scan a project for all the files and directories.
    """
    current_dir = os.getcwd()
    projects = {}

    # Scan the image_name is the directory in top level
    # The image_tag is the directory in the image_name directory
    for image_name in os.listdir(current_dir):
        if os.path.isdir(image_name):
            projects[image_name] = []
            for image_tag in os.listdir(image_name):
                check = os.path.join(image_name, image_tag, "Dockerfile")
                if os.path.isfile(check):
                    projects[image_name].append(image_tag)

    # Filter out the empty image_tags
    projects = {k: v for k, v in projects.items() if v}

    return projects


def get_template_workflows():
    """jinja2 template for Github workflows from string"""

    # Using literal braces to avoid Jinja2 parsing conflicts
    template = """# Generated by gen.py script
# Do not edit this file manually

name: Build and Push
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  REPO: ${{ "{{" }} github.repository {{ "}}" }}

jobs:
  detect-changes:
    name: Detect changed images
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ "{{" }} steps.matrix.outputs.matrix {{ "}}" }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
{% for image_name, image_tags in images.items() %}
{% for image_tag in image_tags %}
            {{ filter_name(image_name, image_tag) }}:
              - '{{ image_name }}/{{ image_tag }}/**'
{% endfor %}
{% endfor %}
            ci_workflow:
              - '.github/workflows/ci.yaml'
          format: json

      - name: Build changed matrix
        id: set-matrix
        run: |
          MATRIX='[]'
{% for image_name, image_tags in images.items() %}
{% for image_tag in image_tags %}
          if [ "${{ "{{" }} steps.changes.outputs.{{ filter_name(image_name, image_tag) }} {{ "}}" }}" == "true" ]; then
            MATRIX=$(echo "$MATRIX" | jq --arg image_name "{{ image_name }}" --arg image_tag "{{ image_tag }}" '. + [{image_name: $image_name, image_tag: $image_tag}]')
          fi
{% endfor %}
{% endfor %}
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

      - name: Build full matrix if workflow changed
        id: matrix
        run: |
          MATRIX="${{ "{{" }} steps.set-matrix.outputs.matrix {{ "}}" }}"
          if [ "${{ "{{" }} steps.changes.outputs.ci_workflow {{ "}}" }}" == "true" ]; then
            MATRIX='[]'
            {% for item in full_matrix %}
            MATRIX=$(echo "$MATRIX" | jq --arg name "{{ item.image_name }}" --arg tag "{{ item.image_tag }}" '. + [{image_name: $name, image_tag: $tag}]')
            {% endfor %}
          fi
          if [ "$MATRIX" == "[]" ]; then
            MATRIX='[{"image_name":"{{ fallback_image }}","image_tag":"{{ fallback_tag }}"}]'
          fi
          echo "matrix=$MATRIX" >> $GITHUB_OUTPUT

  build:
    name: Build ${{ "{{" }} matrix.image_name {{ "}}" }}/${{ "{{" }} matrix.image_tag {{ "}}" }}
    needs: detect-changes
    if: ${{ "{{" }} needs.detect-changes.outputs.matrix != '[]' {{ "}}" }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ "{{" }} fromJson(needs.detect-changes.outputs.matrix) {{ "}}" }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ "{{" }} env.REGISTRY {{ "}}" }}
          username: ${{ "{{" }} github.actor {{ "}}" }}
          password: ${{ "{{" }} secrets.GITHUB_TOKEN {{ "}}" }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ "{{" }} env.REGISTRY {{ "}}" }}/${{ "{{" }} env.REPO {{ "}}" }}
          tags: |
            type=raw,value=${{ "{{" }} matrix.image_tag {{ "}}" }}
            type=raw,value=${{ "{{" }} matrix.image_tag {{ "}}" }}-${{ "{{" }} date('YYYYMMDD') {{ "}}" }}
            type=sha,format=short

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ "{{" }} github.workspace {{ "}}" }}
          file: ./${{ "{{" }} matrix.image_name {{ "}}" }}/${{ "{{" }} matrix.image_tag {{ "}}" }}/Dockerfile
          tags: ${{ "{{" }} steps.meta.outputs.tags {{ "}}" }}
          labels: ${{ "{{" }} steps.meta.outputs.labels {{ "}}" }}
          push: ${{ "{{" }} github.event_name != 'pull_request' {{ "}}" }}

      - name: Image digest
        run: echo ${{ "{{" }} steps.docker_build.outputs.digest {{ "}}" }}
    """

    return template


def filter_name(image_name, image_tag):
    """Generate safe filter name from image name and tag."""
    return f"{image_name}_{image_tag}".replace(".", "_").replace("-", "_")


def build_full_matrix(images):
    """Build full matrix for all images (used when workflow changes)."""
    matrix = []
    for image_name, image_tags in images.items():
        for image_tag in image_tags:
            matrix.append({
                "image_name": image_name,
                "image_tag": image_tag
            })
    return matrix


def get_fallback_image(images):
    """Get a fallback image for safety."""
    for image_name, image_tags in images.items():
        if image_tags:
            return image_name, image_tags[0]
    return "stable-slim", "stable-slim"


def build_workflows(images):
    """Build the workflows yaml for the images."""

    # Get the jinja2 template
    template = jinja2.Template(
        get_template_workflows(),
        trim_blocks=True,
        lstrip_blocks=True
    )

    # Get fallback image
    fallback_name, fallback_tag = get_fallback_image(images)

    # Build the workflows
    workflows = template.render(
        images=images,
        filter_name=filter_name,
        full_matrix=build_full_matrix(images),
        fallback_image=fallback_name,
        fallback_tag=fallback_tag
    )

    # Post-process to replace the literal braces
    workflows = workflows.replace('${{ "{{" }}', "${{")
    workflows = workflows.replace('{{ "}}" }}', "}}")
    workflows = workflows.replace('{{ "{{" }} {{ "}}" }}', "{{")
    workflows = workflows.replace('{{ "}}" }}', "}}")

    # Remove excessive blank lines (more than 2 consecutive)
    import re
    workflows = re.sub(r'\n{3,}', '\n\n', workflows)

    return workflows


def get_template_readme():
    """jinja2 template for README.md from string"""

    template = """

{%- for image_name, image_tags in images.items() | sort %}
- [`{{ image_name }}`](#{{ image_name }})
{%- for image_tag in image_tags | sort %}
    - [`ghcr.io/duyet/docker-images:{{ image_tag }}`](#{{ (image_name + image_tag).lower().replace(" ", "").replace(".", "") }})
{%- endfor %}
{%- endfor %}

{% for image_name, image_tags in images.items() %}
## `{{ image_name }}`

{%- for image_tag in image_tags %}

### [`{{ image_name }}/{{ image_tag }}`]({{ image_name }}/{{ image_tag }}/Dockerfile)

Install from the command line

```bash
docker pull ghcr.io/duyet/docker-images:{{ image_tag }}
```

Use as base image in Dockerfile:

```Dockerfile
FROM ghcr.io/duyet/docker-images:{{ image_tag }}
```
{% endfor %}
{% endfor -%}
    """

    return template


def build_readme(images):
    """Build the README.md for the images."""

    # Get the jinja2 template
    template = jinja2.Template(get_template_readme())

    # Build the workflows
    return template.render(images=images)


if __name__ == "__main__":
    images = scan_images()
    workflows = build_workflows(images)

    # Dry run option
    if "--dry-run" in sys.argv:
        print(workflows)

    # Help option
    if "--help" in sys.argv or "-h" in sys.argv:
        print("Usage:\\n  gen.py [--dry-run | --help]")
        sys.exit(0)

    # Write the workflows to the github workflows directory
    target = ".github/workflows/ci.yaml"
    with open(target, "w", encoding="utf-8") as f:
        f.write(workflows)
        print("Generated workflows to {}".format(target))

    # Generate the README.md
    # Replace content between <!-- BEGIN IMAGE LIST --> and <!-- END IMAGE LIST -->
    # with the list of images
    readme_content = build_readme(images)
    with open("README.md", "r", encoding="utf-8") as f:
        begin = "<!-- BEGIN IMAGE LIST -->"
        end = "<!-- END IMAGE LIST -->"
        content = f.read()
        start = content.find(begin)
        end = content.find(end)
        content = content[:start] + begin + readme_content + content[end:]

    with open("README.md", "w", encoding="utf-8") as f:
        f.write(content)
        print("Generated README.md")
