FROM clickhouse/clickhouse-server:latest

COPY clickhouse-server/testing/config.d/ /etc/clickhouse-server/config.d/
COPY clickhouse-server/testing/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
