FROM clickhouse/clickhouse-server:24.7

COPY clickhouse-server/clickhouse_24.7/config.d/ /etc/clickhouse-server/config.d/
COPY clickhouse-server/clickhouse_24.7/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
