FROM clickhouse/clickhouse-server:head

COPY clickhouse-server/clickhouse_24.9/config.d/ /etc/clickhouse-server/config.d/
COPY clickhouse-server/clickhouse_24.9/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
