FROM postgres:17

# Set default environment variables (can be overridden)
ENV POSTGRES_DB=postgres
ENV POSTGRES_USER=postgres
# ENV POSTGRES_PASSWORD=password

# Copy custom configuration or initialization scripts if needed
# COPY postgresql.conf /etc/postgresql/postgresql.conf
# COPY docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/